# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4fe96ab9aaef6ca80be9f722bdcf9b308944f3775db5025805836c798e7ae97bf6ab3c2a0980244059ed81b1c680b36e06df8dd9d54325a9a7abf9896b62099c

test:
  secret_key_base: 826120db396d9ba62174c8458d31977202681751676a17715acc5f3cdae9badaf09a1de4d84ca84b338601ca5b8d7df37505ebcd53c0b88bcc8b5d8a0a7990bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
